[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
fuzz = { runs = 1000, dictionary_weight = 40, include_storage = true, include_push_bytes = true }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }

# Gas settings for Arbitrum
[profile.gas]
gas_price = 100000000 # 0.1 gwei (Arbitrum uses very low gas)
gas_limit = 10000000

# Test settings
[profile.test]
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15, fail_on_revert = false }
